### ISSUE TITLE
Remove Property Functions (deprecated since 2017)

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-style-spec#188]
This part of the spec is complicated, long time deprecated, undocumented. Would it make sense to remove them or document them?

https://maplibre.org/maplibre-style-spec/deprecations/#function

**Comment by ovivoda** [comment]
@birkskyum if it is long time deprecated I'd say we should remove it

**Comment by JinIgarashi** [comment]
I think “functions” can remain for compatibility of mapbox style.

Those are depreciated since mapbox-gl-js was v1, but they are still supported in mapbox. I think there are still certain users in Mapbox use those functions (that is why Mapbox still does not remove them). I believe some of maplibre users also are using them (To be honest, our[ GeoHub project ](https://github.com/UNDP-Data/geohub) in UNDP  also uses functions).
 
https://docs.mapbox.com/mapbox-gl-js/style-spec/other/#function-stops

I can mostly agree maplibre will move forward different way from mapbox, but I highly recommend to remain certain compatibility with Mapbox style spec since people consider maplibre as an open source version of Mapbox. If maplibre lose compatibility of Mapbox style, it will become more difficult for Mapbox users to migrate to Maplibre.

**Comment by 1ec5** [comment]
To clarify, a “property function” is only one kind of style function. There are also zoom functions and zoom-and-property functions, but [this section of the documentation](https://maplibre.org/maplibre-style-spec/deprecations/#function) conflates all three.

“Removing” style functions could mean three different things. This proposal should be clear about which steps would be taken:

* Removing documentation about style functions. This wouldn’t risk any software breakage, but it could confuse developers as they dive into old styles or Maputnik-generated styles to upgrade them to expressions. Consider documenting the style-spec package’s public utility for converting style functions to expressions and encouraging developers to use it on their styles before functions become obsolete: https://github.com/maplibre/maplibre-style-spec/blob/2c7a6217748de89a23dedb41c16506303213ba40/src/migrate/expressions.ts#L8-L15
* Change the validator to reject style functions as invalid: https://github.com/maplibre/maplibre-style-spec/blob/2c7a6217748de89a23dedb41c16506303213ba40/src/validate/validate_function.ts#L15 This change would not only break compatibility with styles authored in Mapbox Studio for the Mapbox Maps SDKs but also styles authored in editors such as Maputnik for MapLibre: maputnik/editor#711. It would also break older styles authored before MapLibre forked the Mapbox Maps SDKs, as well as MapLibre-powered sites that load Mapbox-targeted styles, such as the OpenStreetMap Wiki. This would be the first breaking change since v8 was released. It would force the next release of this package to be versioned as v9. Libraries such as GL JS would need to accommodate both versions, or even more styles would break.
* Rewrite the underlying implementation of expressions in gl-native to no longer convert `interpolate` and `match` expressions to function-like structures when parsing the style. This would have no backwards compatibility concerns, and it would help to eliminate many frustrating limitations, such as not being able to nest an `interpolate` expression inside of a `+` expression. However, it might be difficult to achieve without revamping the shaders, which I believe are patterned after the original function types.

Style functions are closely related to two other legacy syntaxes: [non-expressions in layer `filter`s](https://maplibre.org/maplibre-style-spec/deprecations/#other-filter) and `{token}`s in `text-field` and `icon-image` (currently undocumented but extremely common). All three were replaced by expressions at the same time and should be considered jointly, because mixing the legacy syntaxes with expressions in the same style creates barriers for GL JS plugins that seek to manipulate the style based on heuristics.

**Comment by zstadler** [comment]
I also think they should remain for compatibility. We use some of them in the [Israel Hiking Maps](https://github.com/IsraelHikingMap/VectorMap/tree/master/Styles) project

**Comment by wipfli** [comment]
Was this discussed in the technical steering committee meeting June 2023?

I remember we talked about the functions some years ago and the conclusion was to keep them because many styles use them and it would be a big breaking change which we should avoid in the spec.

**Comment by birkskyum** [comment]
@wipfli , yes it was discussion. The question was if we should improve documentation or removing the feature, and there was a decision to keep the functionality, and potentially use some of these very informative comments in this thread to extend upon our existing documentation.
