### ISSUE TITLE
Export validate from bundle

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-style-spec#24]
It's necessary to export validate (validate-style.ts) from style-spec.ts, as validate is imported and used in i.e. tileserver gl

**Comment by HarelM** [comment]
I might be stating the obvious, but we need to understand first how to export things without increasing the maplibre-gl-js package size.

**Comment by acalcutt** [comment]
I just want to mention I had brought this up to @birkskyum because tileserver-gl has used validate from the npm package. It uses it to [check the styles](https://github.com/maptiler/tileserver-gl/blob/master/src/serve_style.js#L99) that users are hosting.

tileserver-gl Dependabot picked up this update, but out workflow didn't try to merge it because failed our CT tests due validate being missing
https://github.com/maptiler/tileserver-gl/actions/runs/4266913087/jobs/7427971765

**Comment by HarelM** [comment]
I definitely agree that this should be exported, no doubt, but we need to better understand the mechanics of the maplibre-gl-js package size, something is weird there...

**Comment by HarelM** [comment]
It might be, IDK... But we need to find out...

**Comment by acalcutt** [comment]
Just an FYI. like suggested [I tried](https://github.com/maptiler/tileserver-gl/pull/861/commits/0b39db6a2596c023b8e3121164e1a8f1328433a3) to link directly to validate_style like the bin example, but this didn't seem to work
`import validate from '../node_modules/@maplibre/maplibre-gl-style-spec/src/validate_style';`

Is this because that file is typescript extension while tileserver is not? It gets an error it can't find the module

**Comment by HarelM** [comment]
Yes, probably...

**Comment by HarelM** [comment]
See my comments in the linked PR.
Once all the PRs that I have opened are merged I'll be able to publish a new version.
Happy new year!
