### ISSUE TITLE
Generate expression metadata

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-style-spec#89]
The expression-metadata should be generated rather than hardcoded in the docs.

https://github.com/maplibre/maplibre-style/pull/88/files/45a6e0c9dec8e4f049d922f81ac232afe8837377#diff-c77c8d013c561aabeb096e2cb19647ad9e32566daeab5a6af2cb1137bf4e49ba

**Comment by HarelM** [comment]
@birkskyum can you elaborate here a bit?
The link provided above doesn't lead anywhere.
Is this still an issue? If so how can we solve/close it?

**Comment by birkskyum** [comment]
This is still a bit of an issue - it's just the way the docs are generated from this code, which is quite difficult to understand, and it's almost like this is part of the spec (the expression-metadata mainly).

https://github.com/maplibre/maplibre-style-spec/blob/main/docs/src/expression/expression-types.ts
https://github.com/maplibre/maplibre-style-spec/blob/main/docs/src/expression/expressions.tsx
https://github.com/maplibre/maplibre-style-spec/blob/main/docs/src/expression/expression-metadata.tsx

**Comment by HarelM** [comment]
This is basically the same issue as described in my PR:
- #626 

My suggestion is simply to add `example` for the v8 expression, this way there's no extra work on parsing etc and it is aligned with the rest of the spec.

**Comment by birkskyum** [comment]
I agree that having it in the v8.json would be a great simple approach,

**Comment by HarelM** [comment]
It might be that examples won't cover everything and there might be a need to move the expression syntax definition into the v8.json file.
I'm not entirely sure how to do it yet, but the typescript expression type definition also have this issue where the definition is hard coded into the generation script, see here:
https://github.com/maplibre/maplibre-style-spec/blob/c74b5030cf1749e00958f6ba1617e5019837e976/build/generate-style-spec.ts#L121-L311

My initial thought was to extend the example with something like
```
example: {
  syntax: { "special object for syntax"}, // this will define the parameters and return value
  value: '["any", ... ]' // this is an actual example of the above syntax
}
```

So that the docs generation can use this special example to generate the syntax and example from it and also the typescript generation can use that too.
I think that types page need to be updated with all the return types, otherwise things are not fully defined, IMHO.

@louwers do you have any process in the native repos that takes the v8.json file and generate something from it?

**Comment by louwers** [comment]
Yes we do. We use a very old one though.

**Comment by HarelM** [comment]
Can you elaborate please?

**Comment by louwers** [comment]
We generate wrappers as well as shader code:

Android: https://github.com/maplibre/maplibre-native/blob/main/platform/android/scripts/generate-style-code.js
Core: https://github.com/maplibre/maplibre-native/blob/main/scripts/generate-style-code.js
iOS / macOS: https://github.com/maplibre/maplibre-native/blob/main/platform/darwin/scripts/generate-style-code.js

**Comment by louwers** [comment]
Standardizing on something like JSON Schema is probably a good idea.

**Comment by HarelM** [comment]
I've looked into json scheme, it's easier said than done, the expression syntax is very complicated and creating it in json scheme is not a walk in the park.

I think the above linked code only uses the v8.json file to define the paint and layout properties of different type of layers, as I haven't found any reference to the `expression_name` entry in the v8.json which is responsible for the expression syntax.
So if I needed to guess, the expression syntax is not coming from the v8.json file in any language right now.
